branches:
  - main

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/changelog", { "changelogFile": "CHANGELOG.md" }]
  - ["@semantic-release/github", {
      "assets": [
        { "path": "dist/*.tar.gz", "label": "Zig common library (tar.gz)" },
        { "path": "dist/*.sha256", "label": "SHA256 checksums" }
      ]
    }]
  - ["@semantic-release/git", {
      "assets": ["CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
